### ISSUE TITLE
Feature Request: Add support for DIAMOND

### ISSUE THREAD

**Issue by taltman** [snayfach/MicrobeCensus#5]
I've been using Huson's DIAMOND sequence similarity tool, and have been pleased with its performance. Please consider adding support.

**Comment by snayfach** [comment]
Thanks for this suggestion! In future versions of the software I will consider adding it. Unfortunately it is not as simple as adding a wrapper for the program. I would need to rerun a series of extensive simulations using DIAMOND in order to find necessary parameters (optimal alignment parameters, proportionality constants, family weights).
